# Form implementation generated from reading ui file '.\ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    btnFont = QtGui.QFont()
    btnFont.setPointSize(9)

    line_edit_style = """
            QLineEdit {
                border: 2px solid grey;
                border-radius: 5px;
                font-size:15px;
            }
            """
    btn_style = """
            QPushButton {
                border-radius: 5px;
                background-color: rgb(22, 155, 213);
                color: rgb(255, 255, 255);
            }
            QPushButton:hover {
                border-radius: 5px;
                background-color: rgb(22, 155, 213);
                color: rgb(255, 255, 255);
                border: 2px solid grey;
            }
    """
    def setupUi(self, Dialog):
        Dialog.setObjectName("工具")
        Dialog.resize(653, 417)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 50, 641, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(190, 130, 291, 31))
        self.lineEdit.setStyleSheet(self.line_edit_style)
        self.lineEdit.setPlaceholderText("请选择处理目录")
        font = QtGui.QFont()
        font.setPointSize(3)
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setObjectName("lineEdit")

        self.startBtn = QtWidgets.QPushButton(parent=Dialog)
        self.startBtn.setGeometry(QtCore.QRect(280, 250, 81, 31))
        self.startBtn.setFont(self.btnFont)
        self.startBtn.setText("开始执行")
        self.startBtn.setObjectName("startBtn")
        self.startBtn.setStyleSheet(self.btn_style)

        self.openBtn = QtWidgets.QPushButton(parent=Dialog)
        self.openBtn.setGeometry(QtCore.QRect(480, 310, 81, 31))
        self.openBtn.setObjectName("openBtn")
        self.openBtn.setStyleSheet(self.btn_style)

        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(481, 130, 81, 31))
        self.pushButton.setFont(self.btnFont)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet(self.btn_style)

        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(481, 190, 81, 31))
        self.pushButton_2.setFont(self.btnFont)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet(self.btn_style)

        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 190, 291, 31))
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setStyleSheet(self.line_edit_style)
        self.lineEdit_2.setPlaceholderText("请选择保存目录")

        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 190, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 290, 54, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.status = QtWidgets.QLabel(parent=Dialog)
        self.status.setGeometry(QtCore.QRect(10, 350, 641, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.status.setFont(font)
        self.status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status.setObjectName("status")
        self.bar = QtWidgets.QProgressBar(parent=Dialog)
        self.bar.setGeometry(QtCore.QRect(90, 310, 391, 31))

        self.bar.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.bar.setProperty("value", 0)
        self.bar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bar.setTextVisible(True)
        self.bar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.bar.setInvertedAppearance(False)
        self.bar.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.bar.setObjectName("bar")
        self.bar.setStyleSheet("""
            QProgressBar {
                border: 2px solid grey;
                border-radius: 5px;
                text-align: center;
            }
            QProgressBar::chunk {
                background-color: rgb(22,155,213);
                width: 20px;
            }
        """)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "工具"))
        self.label.setText(_translate("Dialog", "红外相机本地AI识别处理工具"))
        self.label_2.setText(_translate("Dialog", "处理目录："))
        self.pushButton.setText(_translate("Dialog", "选择文件"))
        self.pushButton_2.setText(_translate("Dialog", "选择文件"))
        self.label_3.setText(_translate("Dialog", "保存目录："))
        self.label_4.setText(_translate("Dialog", "进度条"))
        self.status.setText(_translate("Dialog", "待处理"))
        self.openBtn.setText(_translate("Dialog", "打开保存目录"))
